### ISSUE TITLE
其它代码

### ISSUE THREAD

**Issue by 18237031132** [LuoYingSong/MG-WHAR#1]
请问您能上传其它两个数据集的代码吗，很需要

**Comment by LuoYingSong** [comment]
其他数据集的代码没有经过整理，整体编写混乱，我就没有同步到仓库中，如果你有兴趣可以留一个邮箱，理论上也是可以跑的。但是缺少相关文档可能需要你自己研究一下。

**Comment by 18237031132** [comment]
这是我的邮箱：1778934046@qq.com，感谢

**Comment by LuoYingSong** [comment]
链接：https://pan.quark.cn/s/521007fdea17
提取码：WY8m

这里面是原始代码，以及一些中间结果，因此文件比较大而且相对比较混乱，你可以花点时间稍微研究一下代码。由于时代久远，我可能不能给你提供更多帮助了。如果在你编写小论文的时候对你有帮助也希望能引用这篇工作。
